# 作业1

[作业1链接](https://www.kesci.com/home/project/59f29f67c5f3f5119527a2cc)

## 1. 导入numpy库并简写为 np (★☆☆)

In [1]:
import numpy as np

## 2. 打印numpy的版本和配置说明 (★☆☆)

In [2]:
print(np.__version__)
np.show_config()

1.15.1
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Software/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'D:/Software/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Software/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'D:/Sof

## 3. 创建一个长度为10的空向量 (★☆☆)

In [3]:
X = np.zeros(10)
print(X)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## 4. 如何找到任何一个数组的内存大小？ (★☆☆)

In [4]:
Z = np.zeros((10, 10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


## 5. 如何从命令行得到numpy中add函数的说明文档? (★☆☆)

In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

## 6. 创建一个长度为10并且除了第五个值为1的空向量 (★☆☆)

In [6]:
X = np.zeros(10)
X[4] = 1
print(X)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## 7. 创建一个值域范围从10到49的向量(★☆☆)

In [7]:
X = np.arange(10,50)
print(X)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## 8. 反转一个向量(第一个元素变为最后一个) (★☆☆)

In [8]:
X = np.arange(50)
X = X[::-1]
print(X)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


## 9. 创建一个 3x3 并且值从0到8的矩阵(★☆☆)

In [9]:
X = np.arange(9).reshape(3,3)
print(X)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 10. 找到数组[1,2,0,0,4,0]中非0元素的位置索引 (★☆☆)

In [10]:
X = [1, 2, 0, 0, 4, 0]
nz = np.nonzero(X)
print(nz)

(array([0, 1, 4], dtype=int64),)


## 11. 创建一个 3x3 的单位矩阵 (★☆☆)

In [11]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 12. 创建一个 3x3x3的随机数组 (★☆☆)

In [12]:
a = np.random.random((3,3,3))
print(a)

[[[0.60746871 0.24630657 0.67931732]
  [0.17013007 0.73733112 0.2808207 ]
  [0.89042023 0.25979628 0.23061087]]

 [[0.69999641 0.93672528 0.48417161]
  [0.87148578 0.13160871 0.04583753]
  [0.4649751  0.1587687  0.06527681]]

 [[0.95741654 0.96857872 0.94402659]
  [0.89098537 0.76565848 0.56784916]
  [0.93759075 0.99966447 0.86716153]]]


## 13. 创建一个 10x10 的随机数组并找到它的最大值和最小值 (★☆☆)

In [13]:
a = np.random.random((10,10))
print(a.min(), a.max())

0.003336951624031581 0.9895590947131


## 14. 创建一个长度为30的随机向量并找到它的平均值 (★☆☆)

In [14]:
a = np.random.random(30)
m = a.mean
print(m)

<built-in method mean of numpy.ndarray object at 0x000000000581F530>


## 15. 创建一个二维数组，其中边界值为1，其余值为0 (★☆☆)

In [15]:
a = np.ones((10,10))
a[1:-1, 1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## 16. 对于一个存在在数组，如何添加一个用0填充的边界? (★☆☆)

In [16]:
a = np.ones((5,5))
a = np.pad(a, pad_width=1, mode='constant', constant_values=0)
print(a)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


## 17. 以下表达式运行的结果分别是什么? (★☆☆)

In [17]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


## 18. 创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置 (★☆☆)

In [18]:
a = np.diag(1+np.arange(4), k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


## 19. 创建一个8x8 的矩阵，并且设置成棋盘样式 (★☆☆)

In [19]:
a = np.zeros((8,8), dtype=int)
a[::2, ::2] = 1
a[1::2, 1::2] = 1
print(a)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


## 20. 考虑一个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么?

In [20]:
a = np.arange((6*7*8)).reshape(6,7,8)
print(np.unravel_index(100,(6,7,8)))
print(a)

(1, 5, 4)
[[[  0   1   2   3   4   5   6   7]
  [  8   9  10  11  12  13  14  15]
  [ 16  17  18  19  20  21  22  23]
  [ 24  25  26  27  28  29  30  31]
  [ 32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47]
  [ 48  49  50  51  52  53  54  55]]

 [[ 56  57  58  59  60  61  62  63]
  [ 64  65  66  67  68  69  70  71]
  [ 72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87]
  [ 88  89  90  91  92  93  94  95]
  [ 96  97  98  99 100 101 102 103]
  [104 105 106 107 108 109 110 111]]

 [[112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127]
  [128 129 130 131 132 133 134 135]
  [136 137 138 139 140 141 142 143]
  [144 145 146 147 148 149 150 151]
  [152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167]]

 [[168 169 170 171 172 173 174 175]
  [176 177 178 179 180 181 182 183]
  [184 185 186 187 188 189 190 191]
  [192 193 194 195 196 197 198 199]
  [200 201 202 203 204 205 206 207]
  [208 209 210 211 212 213 214 215]
  [216 217 2

## 21. 用tile函数去创建一个 8x8的棋盘样式矩阵(★☆☆)

In [21]:
a = np.array([[1,0],[0,1]])
b = np.tile( a, (4,4) )
print(a)
print(b)

[[1 0]
 [0 1]]
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


## 22. 对一个5x5的随机矩阵做归一化(★☆☆)

In [22]:
a = np.random.random((5,5))
print(a)
amax, amin = a.max(), a.min()
b = (a - amin) / (amax - amin)
print(b)

[[0.81499628 0.88370122 0.26480631 0.49015924 0.79466883]
 [0.09502168 0.52296919 0.19711764 0.26493217 0.86258497]
 [0.46212271 0.98037298 0.80425752 0.14497707 0.50749747]
 [0.68323673 0.29965736 0.28089958 0.22458392 0.36790602]
 [0.94487627 0.43347735 0.58699008 0.61726157 0.15236929]]
[[0.81320782 0.89080971 0.19177091 0.44630596 0.79024806]
 [0.         0.48336463 0.11531689 0.19191307 0.86695901]
 [0.41463883 1.         0.80107844 0.05642437 0.4658894 ]
 [0.66438604 0.23113501 0.20994818 0.14633992 0.30822154]
 [0.95990664 0.38228404 0.55567591 0.58986743 0.06477384]]


## 23. 创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype？(★☆☆)

In [23]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

## 24. 一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？ (★☆☆)

In [24]:
a = np.ones((5,3))
b = np.ones((3,2))
ab = np.dot(a, b)
print(ab)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


## 25. 给定一个一维数组，对其在3到8之间的所有元素取反 (★☆☆)

In [25]:
a = np.arange(11)
a[(2<a)  & (a<9)] *= -1
print(a)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


## 26. 下面脚本运行后的结果是什么? (★☆☆)

In [26]:
print(sum(range(5),-1))

9


In [27]:
from numpy import *
print(sum(range(5),-1))

10


## 27. 考虑一个整数向量Z,下列表达合法的是哪个? (★☆☆)

In [28]:
Z = np.arange(5)
print('1: ', Z**Z)
print('2: ', 2 << Z >> 2)
print('3: ', Z <- Z)
print('4: ', 1j*Z)
print('5: ', Z/1/1)
print('6: ', Z<Z>Z)

1:  [  1   1   4  27 256]
2:  [0 1 2 4 8]
3:  [False False False False False]
4:  [0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
5:  [0. 1. 2. 3. 4.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

## 28. 下列表达式的结果分别是什么?(★☆☆)

In [29]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


D:\Software\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
D:\Software\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


## 29. 如何从零位对浮点数组做舍入 ? (★☆☆)

In [30]:
# Z = np.random.uniform(-10,+10,10)
# print (np.copysign(np.ceil(np.abs(Z)), Z))
a = np.random.uniform(-10,+10,10)
print(a)
b = np.copysign( np.ceil(np.abs(a)), a )
print(b)

[-1.77295021  8.30332685  9.37483725 -3.43786979 -9.94588519  4.46076124
 -3.12885447  9.1571454  -6.9922743  -1.1345741 ]
[ -2.   9.  10.  -4. -10.   5.  -4.  10.  -7.  -2.]


## 30. 如何找到两个数组中的共同元素? (★☆☆)

In [31]:
# Z1 = np.random.randint(0,10,10)
# Z2 = np.random.randint(0,10,10)
# print(np.intersect1d(Z1,Z2))
a = np.random.randint(0,10,10)
print(a)
b = np.random.randint(0,10,10)
print(b)
print(np.intersect1d(a,b))

[7 8 1 5 4 1 5 6 6 1]
[9 3 6 5 1 0 1 6 6 4]
[1 4 5 6]


## 31. 如何忽略所有的 numpy 警告(尽管不建议这么做)? (★☆☆)

In [32]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

In [33]:
# Back to sanity
_ = np.seterr(**defaults)

In [34]:
# An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

## 32. 下面的表达式是正确的吗? (★☆☆)

In [35]:
np.sqrt(-1) == np.emath.sqrt(-1)

D:\Software\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

## 33. 如何得到昨天，今天，明天的日期? (★☆☆)

In [36]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))

Yesterday is 2019-08-04
Today is 2019-08-05
Tomorrow is 2019-08-06


## 34. 如何得到所有与2016年7月对应的日期？ (★★☆)

In [37]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


## 35. 如何直接在位计算(A+B)\*(-A/2)(不建立副本)? (★★☆)

In [38]:
a = np.ones(3) * 1
b = np.ones(3) * 2
np.add(a, b, out=b)

array([3., 3., 3.])

In [39]:
np.divide(a, 2, out=a)

array([0.5, 0.5, 0.5])

In [40]:
np.negative(a, out=a)

array([-0.5, -0.5, -0.5])

In [41]:
np.multiply(a, b, out=a)

array([-1.5, -1.5, -1.5])

## 36. 用五种不同的方法去提取一个随机数组的整数部分(★★☆)

In [42]:
a = np.random.uniform(0,10,10)
print(a)

[4.06324498 3.80961817 6.74678058 4.83317095 3.46802142 2.06941853
 5.26980051 6.4463337  3.24908705 8.99448282]


In [43]:
print('1: ',a - a%1)
print('2: ',np.floor(a))
print('3: ',np.ceil(a) - 1)
print('4: ',a.astype(int))
print('5: ',np.trunc(a))

1:  [4. 3. 6. 4. 3. 2. 5. 6. 3. 8.]
2:  [4. 3. 6. 4. 3. 2. 5. 6. 3. 8.]
3:  [4. 3. 6. 4. 3. 2. 5. 6. 3. 8.]
4:  [4 3 6 4 3 2 5 6 3 8]
5:  [4. 3. 6. 4. 3. 2. 5. 6. 3. 8.]


## 37. 创建一个5x5的矩阵，其中每行的数值范围从0到4 (★★☆)

In [44]:
a = np.zeros((5,5))
print(a)
b = np.arange(5)
print(b)
print(a+b)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[0 1 2 3 4]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


## 38. 通过考虑一个可生成10个整数的函数，来构建一个数组(★☆☆)

In [45]:
def generate():
    for x in range(10):
        yield x
a = np.fromiter(generate(),dtype=float,count=-1)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


## 39. 创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1 (★★☆)

In [46]:
a = np.linspace(0,1,11,endpoint=False)[1:]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [47]:
a = np.random.uniform(0,1,10)
print(a)

[0.22536328 0.44838806 0.31340916 0.38979759 0.56610727 0.23811258
 0.14379083 0.26965983 0.23860674 0.05234491]


## 40. 创建一个长度为10的随机向量，并将其排序 (★★☆)

In [48]:
a = np.random.random(10)
a.sort()
print(a)

[0.00899305 0.06673214 0.07591512 0.21687533 0.25544993 0.36113411
 0.4018821  0.69945056 0.80931768 0.85189818]


## 41.对于一个小数组，如何用比 np.sum更快的方式对其求和？(★★☆)

In [49]:
a = np.arange(10)

In [50]:
%time print(np.sum(a))

%time print(np.add.reduce(a))

45
Wall time: 0 ns
45
Wall time: 1 ms


## 42. 对于两个随机数组A和B，检查它们是否相等(★★☆)

In [51]:
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)
equal_1 = np.allclose(a, b)
print(equal_1)
equal_2 = np.array_equal(a, b)
print(equal_2)

False
False


## 43. 创建一个只读数组(read-only) (★★☆)

In [52]:
a = np.zeros(10)
a.flags.writeable = False
a[0] = 1

ValueError: assignment destination is read-only

## 44. 将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式(★★☆)

In [53]:
# Z = np.random.random((10,2))
# X,Y = Z[:,0], Z[:,1]
# R = np.sqrt(X**2+Y**2)
# T = np.arctan2(Y,X)
# print (R)
# print (T)
a = np.random.random((10,2))
x, y = a[:,0], a[:,1]
print(x, y)
r = np.sqrt(x**2+y**2)
print(r)
t = np.arctan2(y,x)
print(t)

[0.90675662 0.76841319 0.64915212 0.06659079 0.55319083 0.04345772
 0.65315247 0.16360301 0.80936189 0.18406679] [0.42638802 0.55021317 0.62640155 0.3984551  0.25524675 0.44783817
 0.24006275 0.67663986 0.74882721 0.38474626]
[1.00200514 0.94508908 0.90209611 0.40398118 0.60923805 0.44994177
 0.69587231 0.69613752 1.10263723 0.4265094 ]
[0.43955274 0.62140894 0.76756422 1.40520423 0.43230033 1.47406032
 0.35221858 1.33356196 0.74656831 1.12456871]


## 45. 创建一个长度为10的向量，并将向量中最大值替换为1 (★★☆)

In [54]:
a = np.random.random(10)
a[a.argmax()] = 1
print(a)

[0.75716007 0.42833087 0.88560772 1.         0.40471805 0.62696195
 0.81661129 0.27838961 0.49682283 0.57148017]


## 46. 创建一个结构化数组，并实现 x 和 y 坐标覆盖 [0,1]x[0,1] 区域 (★★☆)

In [55]:
a = np.zeros((5,5), [('x',float),('y',float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0,1,5),

                            np.linspace(0,1,5))
print(a)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


## 47. 给定两个数组X和Y，构造Cauchy矩阵C (Cij =1/(xi - yj))

In [56]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(C)
print(np.linalg.det(C))

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]
3638.1636371179666


## 48. 打印每个numpy标量类型的最小值和最大值？ (★★☆)

In [57]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


## 49. 如何打印一个数组中的所有数值? (★★☆)

In [58]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print (Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## 50. 给定标量时，如何找到数组中最接近标量的值？(★★☆)

In [59]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print (Z[index])

76
